### ISSUE TITLE
Test issue

### ISSUE THREAD

**Issue by Zenrac** [nicolas63/JhipsterXamarin#1]

**Comment by roeticvampire** [comment]
Hi there, can I help you with this issue?

**Comment by nicolas63** [comment]
hello @roeticvampire, this project is a student project whose goal is to create a first template to enrich Jhipster.net (https://github.com/jhipster/jhipster-dotnetcore)
If you want to contribute you can of course and I can help you to find a good issue, and help you in the realization of this one.
